### ISSUE TITLE
0.4.1 release on npm removes all code?

### ISSUE THREAD

**Issue by aautar** [vinsonchuong/jasmine-es6#14]
I see that this has been deprecated in favor of Ava, but the latest v0.4.1 package published on npm doesn't include any code. This will, of course, break projects that include `jasmine-es6` as a dependency with the version specified via something like `^0.4.0` or `~0.4.0`.

AFAIK, jasmine doesn't have complete ES6 support, and Ava isn't a drop-in replacement for jasmine, so I do think there is still some value is keeping this package up.

**Comment by vinsonchuong** [comment]
I've re-released a previous version as 0.4.3. Thanks for the thoughtful post!
