### ISSUE TITLE
Difference in setup

### ISSUE THREAD

**Issue by mauvm** [vinsonchuong/jasmine-es6#3]
I didn't get this package to work with Babel 6, so I've setup up my own - quick and dirty - solution. I'm wondering how `jasmine-es6` differs from my setup:

https://gist.github.com/mauvm/172878a9646095d03fd7

PS: Not meant sarcastically, I'm genuinely interested.

**Comment by vinsonchuong** [comment]
Hey, sorry for taking so long to respond. `jasmine-es6` is esentially your gist wrapped up into an executable. It also enables you to use `async` and `await` without requiring your test cases to take a `done` argument. The dream is to free users from having to worry about how to configure Babel and to be able to just use ES.next. Fortunately, I have upgraded to Babel 6.
