### ISSUE TITLE
Is destructuring assignment supported?

### ISSUE THREAD

**Issue by jeromecovington** [vinsonchuong/jasmine-es6#4]
I am encountering an error on running my tests that would seem to imply that destructuring assignment is not supported. Is that the case?

```
var {ApplicationStore, MetaStore} = require('../stores');
    ^

SyntaxError: Unexpected token {
```

Just to be thorough, this is my `jasmine.json`

```
{
  "spec_dir": "test",
  "spec_files": [
    "**/*spec.js"
  ],
  "helpers": [
    "../node_modules/jasmine-es6/lib/install.js",
    "helpers/**/*.js"
  ]
}
```

**Comment by vinsonchuong** [comment]
Hello, I apologize for being unresponsive. I'll try to keep on top of GitHub issues moving forward.

I'm not sure whether you've solved this particular problem or moved on to another package; so, I'll close this issue. If you're still interested in finding a solution to this problem, I'd be happy to look into it.

**Comment by jeromecovington** [comment]
Yeah I ended up doing this:

```
{
  "spec_dir": "test",
  "spec_files": [
    "**/*spec.js"
  ],
  "helpers": [
    "../node_modules/babel-core/register.js",
    "helpers/**/*.js"
  ]
}
```

All is well, thanks for checking.
