### ISSUE TITLE
Babel 6?

### ISSUE THREAD

**Issue by thealjey** [vinsonchuong/jasmine-es6#5]

**Comment by gavacho** [comment]
This helped me: https://gist.github.com/mauvm/172878a9646095d03fd7

**Comment by thealjey** [comment]
@gavacho so, your suggestion is to just basically not use `jasmine-es6`))) LOL :smiling_imp:

**Comment by vinsonchuong** [comment]
Hey @thealjey, it's taken a while to update to Babel 6 due to the babel-runtime not working with async/await (https://phabricator.babeljs.io/T6644). That issue has since been resolved; so, I'll have something out in the next few days.

**Comment by vinsonchuong** [comment]
The latest version `0..1.0` is now on Babel 6.
