### ISSUE TITLE
Errors are not logged to the console

### ISSUE THREAD

**Issue by ghost** [vinsonchuong/jasmine-es6#6]
Hi, thanks for creating this. 

When there is an error in my spec, for example I try to import a file that doesn't exist(but any error really), then it's not logged to the console. Jasmine-es6 just prints nothing to the console and exits with a status code of 0 (Success). I confirmed this by writing everything in es5 and running normal jasmine. 

I'll see if I can get a chance to dig into the code and see if I can find out why.

**Comment by vinsonchuong** [comment]
Thanks for the heads up! I wouldn't have noticed if you didn't bring it up. I'll also start to look into it as well. Let me know if you figure something out!

**Comment by ghost** [comment]
Pleasure, I've not looked into it further but what I have noticed it's not on all errors as I thought originally. It seems to be syntax errors that fails silently.

**Comment by vinsonchuong** [comment]
I've released version `0.1.8` with the above commit. Let me know if this addresses the issue that you're running into. I'll keep the issue open until we verify that you're good to go.

**Comment by ghost** [comment]
Thanks :+1: , that did the trick. Getting the errors now.

**Comment by vinsonchuong** [comment]
Glad I could help!
