### ISSUE TITLE
Using jasmine-es6 within a script

### ISSUE THREAD

**Issue by mildfuzz** [vinsonchuong/jasmine-es6#7]
My assumption was that, as I could use this in place of Jasmine in the command line, that I could also use this as a replacement for Jasmine within a node script, thusly:

``` js
var Jasmine = require('jasmine-es6');
var jasmine = new Jasmine();
jasmine.loadConfigFile('spec/support/jasmine.json');
```

This falls over in a couple of places. Firstly the module does not return a function, so line 2 is in valid. Secondly, if we skip the constructor step (and reassign var's appropriately) we do not have the loadConfigFile method

Can this be used within a script?

**Comment by vinsonchuong** [comment]
`jasmine-es6` currently doesn't export a JS interface like `jasmine` does, but I can walk you through what its doing. You can manually recover all of what `jasmine-es6` provides as follows:

First, it loads the Babel require hook, which overrides `require` to compile ES2015 files:

``` js
require('babel-register')({
  presets: ['es2015', 'stage-0'],
  plugins: ['transform-decorators-legacy', 'transform-runtime']
});
```

Then, it loads `jasmine-es6/lib/install` as a helper via Jasmine's configuration API, which overrides `it`, etc. to support `async` functions:

``` json
{
  "helpers": [
    "../node_modules/jasmine-es6/lib/install.js"
  ]
}
```
